# Generated by Django 5.2.17 on 2026-08-21 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or title of the donation camp.', max_length=255)),
                ('location', models.CharField(help_text='Physical venue or location of the camp.', max_length=255)),
                ('camp_date', models.DateField(help_text='Scheduled date for the donation camp.')),
                ('organizer', models.CharField(help_text='Organizing institution, NGO, college, or corporate sponsor.', max_length=255)),
                ('target_units', models.PositiveIntegerField(help_text='Target units of blood expected to be collected (must be greater than 0).', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, default='', help_text='Additional details, camp timing, instructions, or notes.')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', help_text='Current lifecycle status of the donation camp.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(help_text='Blood bank facility organizing this donation camp.', on_delete=django.db.models.deletion.CASCADE, related_name='donation_camps', to='inventory.bloodbank')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the donation camp record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donation_camps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Camp',
                'verbose_name_plural': 'Donation Camps',
                'db_table': 'donation_camps',
                'ordering': ['-camp_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the donation occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(help_text='Blood bank where the blood was collected or processed.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='inventory.bloodbank')),
                ('blood_unit', models.OneToOneField(help_text='Physical blood unit collected from this donation.', on_delete=django.db.models.deletion.PROTECT, related_name='donation', to='inventory.bloodunit')),
                ('created_by', models.ForeignKey(blank=True, help_text='Blood bank administrator user who recorded this donation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(help_text='Donor who gave blood.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor')),
                ('camp', models.ForeignKey(blank=True, help_text='Optional donation camp where blood was collected (null for walk-ins).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcamp')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationCampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended')], default='REGISTERED', help_text='Registration status (REGISTERED, CANCELLED, ATTENDED).', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the donor registered.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(help_text='Donation camp the donor is registering for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='donations.donationcamp')),
                ('donor', models.ForeignKey(help_text='Donor registering for the camp.', on_delete=django.db.models.deletion.CASCADE, related_name='camp_registrations', to='donors.donor')),
            ],
            options={
                'verbose_name': 'Donation Camp Registration',
                'verbose_name_plural': 'Donation Camp Registrations',
                'db_table': 'donation_camp_registrations',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('donor', 'camp'), name='unique_donor_camp_registration')],
            },
        ),
    ]
