# Generated by Django 5.2.17 on 2026-08-20 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_result', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', help_text='HIV antibody/antigen screening result.', max_length=20)),
                ('hepatitis_b_result', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', help_text='Hepatitis B surface antigen (HBsAg) screening result.', max_length=20)),
                ('hepatitis_c_result', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', help_text='Hepatitis C antibody (Anti-HCV) screening result.', max_length=20)),
                ('syphilis_result', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', help_text='Syphilis (VDRL/RPR) screening result.', max_length=20)),
                ('malaria_result', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', help_text='Malaria parasite screening result.', max_length=20)),
                ('tested_at', models.DateTimeField(blank=True, help_text='Timestamp when the laboratory testing was recorded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_unit', models.OneToOneField(help_text='Blood unit undergoing laboratory screening.', on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='inventory.bloodunit')),
                ('tested_by', models.ForeignKey(blank=True, help_text='Laboratory technician who conducted or updated the test results.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'db_table': 'test_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
