# Generated by Django 5.2.17 on 2026-08-21 16:17

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile display picture.', null=True, upload_to=apps.accounts.models.user_profile_image_path),
        ),
    ]
