# Generated by Django 5.2.17 on 2026-09-04 06:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Physical address or location description.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='User coordinate latitude (-90.0 to 90.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='User coordinate longitude (-180.0 to 180.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))]),
        ),
    ]
