# Generated by Django 5.2.17 on 2026-08-19 17:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Verified or self-reported ABO and Rh blood group.', max_length=5)),
                ('date_of_birth', models.DateField(help_text='Date of birth to verify age eligibility (18–65 years).')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Body weight in kilograms (minimum 50.0 kg required for donation).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Donor coordinate latitude for emergency radius matching.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Donor coordinate longitude for emergency radius matching.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('last_donation_date', models.DateField(blank=True, help_text='Date of the most recent blood donation (null for first-time donors).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account associated with this donor profile.', on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'db_table': 'donors',
                'ordering': ['-created_at'],
            },
        ),
    ]
