# Generated by Django 5.2.17 on 2026-08-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
        ('notifications', '0002_alter_notification_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', help_text='Current operational status of this SOS broadcast.', max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Target requested blood group.', max_length=5)),
                ('units_needed', models.PositiveIntegerField(help_text='Total blood units required by the critical request.')),
                ('available_units_at_trigger', models.PositiveIntegerField(help_text='Available stock units at the target blood bank when broadcast was triggered.')),
                ('shortage_units', models.PositiveIntegerField(help_text='Quantity shortage (units_needed - available_units_at_trigger).')),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, help_text='Optional geographical radius filter applied in kilometers.', max_digits=6, null=True)),
                ('total_donors_targeted', models.PositiveIntegerField(default=0, help_text='Total count of eligible compatible donors notified.')),
                ('title', models.CharField(help_text='Broadcast summary title.', max_length=255)),
                ('message', models.TextField(help_text='Emergency broadcast message sent to donors.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when SOS broadcast was triggered.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when SOS broadcast was last updated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when SOS broadcast was marked completed.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when SOS broadcast was cancelled.', null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Explanation for cancellation.')),
                ('blood_request', models.ForeignKey(help_text='Critical blood request that triggered this emergency broadcast.', on_delete=django.db.models.deletion.CASCADE, related_name='sos_broadcasts', to='blood_requests.bloodrequest')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Staff or admin user who cancelled the broadcast.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sos_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(help_text='Staff member who authorized the emergency broadcast.', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_sos_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Broadcast',
                'verbose_name_plural': 'SOS Broadcasts',
                'db_table': 'sos_broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.BooleanField(default=False, help_text='Designates whether email dispatch was attempted.')),
                ('email_sent', models.BooleanField(default=False, help_text='Designates whether email dispatch succeeded.')),
                ('delivery_error', models.TextField(blank=True, default='', help_text='Safe error description if email delivery failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when recipient was notified.')),
                ('donor', models.ForeignKey(help_text='Targeted donor profile.', on_delete=django.db.models.deletion.CASCADE, related_name='sos_deliveries', to='donors.donor')),
                ('notification', models.ForeignKey(blank=True, help_text='Generated in-app notification record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_delivery_audit', to='notifications.notification')),
                ('sos_broadcast', models.ForeignKey(help_text='Associated SOS broadcast.', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='emergency_sos.sosbroadcast')),
                ('user', models.ForeignKey(help_text='User account associated with the donor.', on_delete=django.db.models.deletion.CASCADE, related_name='sos_notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Recipient',
                'verbose_name_plural': 'SOS Recipients',
                'db_table': 'sos_recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sosbroadcast',
            index=models.Index(fields=['blood_request', 'status'], name='sos_broadca_blood_r_5646a9_idx'),
        ),
        migrations.AddIndex(
            model_name='sosbroadcast',
            index=models.Index(fields=['status', '-created_at'], name='sos_broadca_status_e6d317_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrecipient',
            index=models.Index(fields=['sos_broadcast', 'donor'], name='sos_recipie_sos_bro_abd861_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrecipient',
            index=models.Index(fields=['user', '-created_at'], name='sos_recipie_user_id_6c38fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosrecipient',
            unique_together={('sos_broadcast', 'donor')},
        ),
    ]
