# Generated by Django 5.2.17 on 2026-09-04 10:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0003_alter_bloodrequest_blood_group'),
        ('inventory', '0002_alter_bloodunit_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Numerical rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Detailed feedback or review commentary.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Moderation status (PENDING, APPROVED, REJECTED).', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the review was moderated.', null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Optional explanation recorded if the review is rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(blank=True, help_text='Target blood bank facility.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.bloodbank')),
                ('hospital', models.ForeignKey(blank=True, help_text='Target hospital facility.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blood_requests.hospital')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrator who reviewed and decided upon this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Authenticated user who submitted this review.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Review',
                'verbose_name_plural': 'Facility Reviews',
                'db_table': 'facility_reviews',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hospital__isnull', False), ('blood_bank__isnull', True)), models.Q(('hospital__isnull', True), ('blood_bank__isnull', False)), _connector='OR'), name='review_must_target_exactly_one_facility')],
            },
        ),
    ]
