# Generated by Django 5.2.17 on 2026-08-20 01:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the blood bank facility.', max_length=255)),
                ('address', models.TextField(blank=True, default='', help_text='Physical street address of the blood bank.')),
                ('city', models.CharField(help_text='City where the blood bank is situated.', max_length=100)),
                ('state', models.CharField(help_text='State or province.', max_length=100)),
                ('contact_number', models.CharField(help_text='Primary telephone/contact number.', max_length=30)),
                ('email', models.EmailField(help_text='Official contact email address.', max_length=254)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum total blood unit storage capacity (units).', validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for geographical location (-90.0 to 90.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for geographical location (-180.0 to 180.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this blood bank is actively operational.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Assigned Blood Bank Administrator user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blood_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Bank',
                'verbose_name_plural': 'Blood Banks',
                'db_table': 'blood_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(db_index=True, help_text='Unique, human-readable identifier for this blood unit.', max_length=60, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='ABO and Rh blood group.', max_length=5)),
                ('collection_date', models.DateField(help_text='Date the blood unit was collected from the donor.')),
                ('expiry_date', models.DateField(help_text='Expiry date calculated strictly as collection_date + 42 days.')),
                ('status', models.CharField(choices=[('TESTING', 'Testing'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('DISPATCHED', 'Dispatched'), ('DISCARDED', 'Discarded')], default='TESTING', help_text='Current lifecycle and quality status of the blood unit.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(help_text='Blood bank where this unit is stored.', on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='inventory.bloodbank')),
            ],
            options={
                'verbose_name': 'Blood Unit',
                'verbose_name_plural': 'Blood Units',
                'db_table': 'blood_units',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
