/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAuditLogsRouteImport } from './routes/app.audit-logs'
import { Route as AppBloodBanksRouteImport } from './routes/app.blood-banks'
import { Route as AppCampsRouteImport } from './routes/app.camps'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDonationHistoryRouteImport } from './routes/app.donation-history'
import { Route as AppDonorsRouteImport } from './routes/app.donors'
import { Route as AppEmailsRouteImport } from './routes/app.emails'
import { Route as AppHospitalsRouteImport } from './routes/app.hospitals'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRequestHistoryRouteImport } from './routes/app.request-history'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSosRouteImport } from './routes/app.sos'
import { Route as AppTestHistoryRouteImport } from './routes/app.test-history'
import { Route as AppTestsRouteImport } from './routes/app.tests'
import { Route as AppUsersRouteImport } from './routes/app.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppBloodBanksRoute = AppBloodBanksRouteImport.update({
  id: '/blood-banks',
  path: '/blood-banks',
  getParentRoute: () => AppRoute,
} as any)
const AppCampsRoute = AppCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationHistoryRoute = AppDonationHistoryRouteImport.update({
  id: '/donation-history',
  path: '/donation-history',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsRoute = AppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestHistoryRoute = AppRequestHistoryRouteImport.update({
  id: '/request-history',
  path: '/request-history',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppTestHistoryRoute = AppTestHistoryRouteImport.update({
  id: '/test-history',
  path: '/test-history',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/blood-banks': typeof AppBloodBanksRoute
  '/app/camps': typeof AppCampsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donation-history': typeof AppDonationHistoryRoute
  '/app/donors': typeof AppDonorsRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request-history': typeof AppRequestHistoryRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/test-history': typeof AppTestHistoryRoute
  '/app/tests': typeof AppTestsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/availability': typeof AvailabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/blood-banks': typeof AppBloodBanksRoute
  '/app/camps': typeof AppCampsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donation-history': typeof AppDonationHistoryRoute
  '/app/donors': typeof AppDonorsRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request-history': typeof AppRequestHistoryRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/test-history': typeof AppTestHistoryRoute
  '/app/tests': typeof AppTestsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/blood-banks': typeof AppBloodBanksRoute
  '/app/camps': typeof AppCampsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donation-history': typeof AppDonationHistoryRoute
  '/app/donors': typeof AppDonorsRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request-history': typeof AppRequestHistoryRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/test-history': typeof AppTestHistoryRoute
  '/app/tests': typeof AppTestsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/availability'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/blood-banks'
    | '/app/camps'
    | '/app/dashboard'
    | '/app/donation-history'
    | '/app/donors'
    | '/app/emails'
    | '/app/hospitals'
    | '/app/inventory'
    | '/app/map'
    | '/app/notifications'
    | '/app/profile'
    | '/app/request-history'
    | '/app/requests'
    | '/app/settings'
    | '/app/sos'
    | '/app/test-history'
    | '/app/tests'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/availability'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/blood-banks'
    | '/app/camps'
    | '/app/dashboard'
    | '/app/donation-history'
    | '/app/donors'
    | '/app/emails'
    | '/app/hospitals'
    | '/app/inventory'
    | '/app/map'
    | '/app/notifications'
    | '/app/profile'
    | '/app/request-history'
    | '/app/requests'
    | '/app/settings'
    | '/app/sos'
    | '/app/test-history'
    | '/app/tests'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/availability'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/blood-banks'
    | '/app/camps'
    | '/app/dashboard'
    | '/app/donation-history'
    | '/app/donors'
    | '/app/emails'
    | '/app/hospitals'
    | '/app/inventory'
    | '/app/map'
    | '/app/notifications'
    | '/app/profile'
    | '/app/request-history'
    | '/app/requests'
    | '/app/settings'
    | '/app/sos'
    | '/app/test-history'
    | '/app/tests'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AvailabilityRoute: typeof AvailabilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blood-banks': {
      id: '/app/blood-banks'
      path: '/blood-banks'
      fullPath: '/app/blood-banks'
      preLoaderRoute: typeof AppBloodBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/camps': {
      id: '/app/camps'
      path: '/camps'
      fullPath: '/app/camps'
      preLoaderRoute: typeof AppCampsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donation-history': {
      id: '/app/donation-history'
      path: '/donation-history'
      fullPath: '/app/donation-history'
      preLoaderRoute: typeof AppDonationHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donors': {
      id: '/app/donors'
      path: '/donors'
      fullPath: '/app/donors'
      preLoaderRoute: typeof AppDonorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emails': {
      id: '/app/emails'
      path: '/emails'
      fullPath: '/app/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hospitals': {
      id: '/app/hospitals'
      path: '/hospitals'
      fullPath: '/app/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/request-history': {
      id: '/app/request-history'
      path: '/request-history'
      fullPath: '/app/request-history'
      preLoaderRoute: typeof AppRequestHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sos': {
      id: '/app/sos'
      path: '/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/test-history': {
      id: '/app/test-history'
      path: '/test-history'
      fullPath: '/app/test-history'
      preLoaderRoute: typeof AppTestHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests': {
      id: '/app/tests'
      path: '/tests'
      fullPath: '/app/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBloodBanksRoute: typeof AppBloodBanksRoute
  AppCampsRoute: typeof AppCampsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonationHistoryRoute: typeof AppDonationHistoryRoute
  AppDonorsRoute: typeof AppDonorsRoute
  AppEmailsRoute: typeof AppEmailsRoute
  AppHospitalsRoute: typeof AppHospitalsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMapRoute: typeof AppMapRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRequestHistoryRoute: typeof AppRequestHistoryRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppTestHistoryRoute: typeof AppTestHistoryRoute
  AppTestsRoute: typeof AppTestsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBloodBanksRoute: AppBloodBanksRoute,
  AppCampsRoute: AppCampsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDonationHistoryRoute: AppDonationHistoryRoute,
  AppDonorsRoute: AppDonorsRoute,
  AppEmailsRoute: AppEmailsRoute,
  AppHospitalsRoute: AppHospitalsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMapRoute: AppMapRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRequestHistoryRoute: AppRequestHistoryRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppTestHistoryRoute: AppTestHistoryRoute,
  AppTestsRoute: AppTestsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AvailabilityRoute: AvailabilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
