# Generated by Django 5.2.17 on 2026-08-20 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Requested ABO and Rh blood group.', max_length=5)),
                ('units_needed', models.PositiveIntegerField(help_text='Number of blood units needed (must be at least 1).', validators=[django.core.validators.MinValueValidator(1)])),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', help_text='Clinical urgency level of the request.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current processing status of the blood request.', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason provided by the Blood Bank Administrator if the request is rejected.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was approved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Blood bank administrator user who approved this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blood_requests', to=settings.AUTH_USER_MODEL)),
                ('blood_bank', models.ForeignKey(help_text='Target blood bank facility.', on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='inventory.bloodbank')),
                ('hospital_staff', models.ForeignKey(help_text='Hospital staff user who submitted this blood request.', on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
                ('reserved_units', models.ManyToManyField(blank=True, help_text='Specific BloodUnit entities reserved for this approved request.', related_name='reserved_for_requests', to='inventory.bloodunit')),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'db_table': 'blood_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
