# Generated by Django 5.2.17 on 2026-09-04 06:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the hospital facility.', max_length=255)),
                ('address', models.TextField(blank=True, default='', help_text='Physical street address of the hospital.')),
                ('city', models.CharField(help_text='City where the hospital is situated.', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State or province.', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', help_text='Primary telephone / emergency desk contact number.', max_length=30)),
                ('email', models.EmailField(blank=True, default='', help_text='Official contact email address.', max_length=254)),
                ('beds', models.PositiveIntegerField(default=0, help_text='Approved inpatient bed capacity.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (-90.0 to 90.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (-180.0 to 180.0).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the hospital is actively partnered on the platform.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
    ]
