# Generated by Django 5.2.17 on 2026-08-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Validated unique email address for communication.', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Recipient full name, organization, or department.', max_length=150)),
                ('recipient_type', models.CharField(choices=[('ADMIN', 'Administrator'), ('BLOOD_BANK', 'Blood Bank Coordinator'), ('HOSPITAL', 'Hospital Contact'), ('STAFF', 'Staff Member'), ('GENERAL', 'General Subscriber'), ('EMERGENCY_DESK', 'Emergency Desk Contact')], default='GENERAL', help_text='Role classification of the email recipient.', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether automated communications are active for this recipient.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when recipient was registered.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when recipient record was last updated.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrator who registered this recipient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_recipients', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Optional associated system User account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Recipient',
                'verbose_name_plural': 'Email Recipients',
                'db_table': 'email_recipients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='email_recip_email_31770b_idx'), models.Index(fields=['recipient_type', 'is_active'], name='email_recip_recipie_b2f1ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Concise summary title of the notification.', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification content body.')),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General Notification'), ('SYSTEM', 'System Alert'), ('BLOOD_REQUEST', 'Blood Request Update'), ('DONATION', 'Donation Update'), ('CAMP', 'Donation Camp Update'), ('ELIGIBILITY', 'Donor Eligibility Alert'), ('INVENTORY', 'Inventory Notice'), ('SOS', 'Emergency Alert')], default='GENERAL', help_text='Category of the notification.', max_length=30)),
                ('is_read', models.BooleanField(default=False, help_text='Designates whether the recipient has read this notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when notification was generated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when notification was last updated.')),
                ('recipient', models.ForeignKey(help_text='User receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_b1a229_idx')],
            },
        ),
    ]
